# Dependencies
markdown:    kramdown
highlighter: pygments

gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap

comments:
  disqus: "justcodingthings"

sass:
  sass_dir: _sass

include:
 - .nojekyll


# Permalinks
permalink:   pretty

# Setup
title:             'Just Coding Things'
tagline:           'Life, Programming and Stuff'
description:       'Life, Programming and Stuff'
url:               'http://wanderwaltz.github.io'
baseurl:           /
excerpt_separator: '<!--more-->'
more:              'Read'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Egor Chiglintsev"


author:
  name:   'Egor Chiglintsev'
  email:  wanderwaltz@gmail.com
  url:    https://github.com/wanderwaltz

paginate: 5

# Ignored files
exclude:
  - 'Rakefile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE.md'
