title: Never Stop Learning
email: wanderwaltz@gmail.com
description: >-
 Yet another tech blog by Wanderwaltz. iOS, Swift and a little bit of this and that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wanderwaltz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wanderwaltz
github_username: wanderwaltz

# Build settings
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
