title: "#justcodingthings"
author: "Egor Chiglintsev"
description: "Yet another tech blog related to various coding stuff I encounter in my everyday life."
more: "Read"
url: "http://wanderwaltz.github.io/about"

comments:
    disqus: "justcodingthings"

style:
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#ffffff"

sass:
  sass_dir: _sass
  style: compressed

links:
  - github: "https://github.com/wanderwaltz/"
  - twitter: "https://twitter.com/wanderwaltz/"
  - rss: "http://wanderwaltz.github.io/feed.xml"

excerpt_separator: "<!--more-->"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]