# Dependencies
markdown:    kramdown
highlighter: pygments

gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-feed
 - jekyll-sitemap

comments:
  disqus: "justcodingthings"

sass:
  sass_dir: _sass

feed:
  path: feed.xml

include:
 - .nojekyll


# Permalinks
permalink:   pretty

# Setup
title:             'Just Coding Things'
tagline:           'A Jekyll theme'
description:       'Yet another tech blog related to various coding stuff I encounter in my everyday life.'
baseurl:           /
excerpt_separator: '<!--more-->'
more:              'Read'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


author:
  name:      'Egor Chiglintsev'
  url:       https://github.com/wanderwaltz

paginate:    5
